import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorial: [{ type: 'autogenerated', dirName: 'tutorial' }],
  bff: [{ type: 'autogenerated', dirName: 'bff' }],
  e2e: [{ type: 'autogenerated', dirName: 'e2e' }],
  fe: [{ type: 'autogenerated', dirName: 'fe' }],
  setup: [{ type: 'autogenerated', dirName: 'setup' }],
  simulator: [{ type: 'autogenerated', dirName: 'simulator' }],
}

export default sidebars
