name: e2e-ios

on: push

jobs:
  install-e2e-dependencies:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: e2e
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 22

      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile --prefer-offline

  install-frontend-dependencies:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: fe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 22

      - name: Install Yarn dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3.4

      # === Install CocoaPods ===
      # Only install CocoaPods if the cache is not hit
      - name: Cache CocoaPods
        id: cache-cocoapods
        uses: actions/cache@v4
        with:
          path: fe/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        run: cd ios && pod install
        working-directory: fe
      # === Install CocoaPods ===

  e2e-ios:
    runs-on: macos-latest
    needs: [install-e2e-dependencies, install-frontend-dependencies]
    defaults:
      run:
        working-directory: e2e
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v4
        with:
          path: ios/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build

      - name: Detox build
        run: yarn build:ios:ci

      - name: Detox test
        run: yarn test:ios:ci

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detox-artifacts
          path: artifacts
